### ISSUE TITLE
Help me add an indicator

### ISSUE THREAD

**Issue by PPMagick** [FokiDoki/WireRest#72]
I want an indicator that will show the number of peers that are currently connected to the server, in digital form or as a fill scale, please help

**Comment by FokiDoki** [comment]
Hello! At this time, the WireRest monitoring endpoint does not provide any data about currently connected peers. But you can make your own exporter based on WireRest. 

You can get information about currently connected users by sending a request to `/v1/peers`. [Docs](http://wr-demo.fokidoki.su:8081/webjars/swagger-ui/index.html#/Peers/getPeers)
```
curl -X 'GET' \
  'http://WIREREST_IP:WIREREST_PORT/v1/peers?sort=lastHandshakeTime.DESC' \
  -H 'accept: application/json'
```
There is `latestHandshake` timestamp when user was connected last time. 
Then you need to select a time that will conditionally indicate that the user is connected (timeout). 5 minutes, for example. And accordingly `if currentTimestamp-timeout-peerTimestamp<=0` then the user is connected.
